buildscript {
    // 1. Kotlin sürümünü buraya ekledik (Hatanın çözümü bu)
    ext.kotlin_version = '2.2.20'
    
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // 2. Android derleme aracını güncelledik
        classpath 'com.android.tools.build:gradle:8.11.1'
        
        // 3. Kotlin eklentisini ekledik (Java 17 ile uyumlu olması için)
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        
        // 4. Senin eklediğin Firebase servisi
        classpath 'com.google.gms:google-services:4.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
